use_frameworks!

platform :ios, '9.0'

target 'PRKit_Example' do
  pod 'PRKit', :path => '../'

  target 'PRKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
