use_frameworks!

platform :ios, '12.4'

target 'PRKit_Example' do
  pod 'PRKit', :path => '../'
  pod 'SwiftLint'

  target 'PRKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
